config/routes.rb
Current::Application.routes.draw do

  root :to => "home#index"

  controller :sessions do
    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end

  get 'admin' => 'admin#index'

  namespace :admin do
    resources :alternatives
    resources :decisions
    resources :users
    resources :voters
    resources :votes, :except => [:new, :create, :edit, :update, :destroy]
  end

  resources :decision, :except => [:index, :create, :new, :show, :update, :edit, :destroy]

  get 'decision/:slug' => 'decision#new'

  post 'decision/:slug' => 'decision#create'

end

app/models/voter.rb
class Voter < ActiveRecord::Base

  has_many :votes

  class << self
    attr_accessor :ui_fields
  end

  self.ui_fields = [:email, :token, :public_identifier, :hashed_secret, :salt]

end

app/controllers/admin/voters_controller.rb
class Admin::VotersController < ::AdminController
  respond_to :html, :json
  does :everything
end

app/views/admin/voters/_form.html.erb
<%= form_for([:admin, @voter]) do |f| %>
  <% if @voter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voter.errors.count, "error") %> prohibited this voter from being saved:</h2>

      <ul>
      <% @voter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <% @voter.class.ui_fields.map(&:intern).each do |k| %>
    <div class="field">
      <%= f.label k %><br />
      <%= f.text_field k %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/voters/edit.html.erb
<h1>Editing voter</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_voter_path(@voter) %> |
<%= link_to 'Back', admin_voters_path %>

app/views/admin/voters/index.html.erb
<h1>Listing voters</h1>

<table>
  <tr>
    <% v = Voter.new; f = nil; form_for(:admin, v) {|ff| f = ff } # @todo hack %>
    <% v.class.ui_fields.map(&:intern).each do |k| %>
      <th> <%= f.label(k) %> </th>
    <% end %>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @voters.each do |voter| %>
  <tr>
    <% Voter.ui_fields.map(&:intern).each do |k| %>
      <td><%= voter.send(k) %></td>
    <% end %>
    <td><%= link_to 'Show', admin_voter_path(voter) %></td>
    <td><%= link_to 'Edit', edit_admin_voter_path(voter) %></td>
    <td><%= link_to 'Destroy', admin_voter_path(voter), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Voter', new_admin_voter_path %>

app/views/admin/voters/new.html.erb
<h1>New voter</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_voters_path %>

app/views/admin/voters/show.html.erb
<p id="notice"><%= notice %></p>

<% f = nil; form_for(:admin, Voter.new) {|ff| f = ff } # @todo hack %>

<% @voter.class.ui_fields.map(&:intern).each do |k| %>
  <p>
    <b><%= f.label(k) %>:</b>
    <%= @voter.send(k) %>
  </p>
<% end %>

<%= link_to 'Edit', edit_admin_voter_path(@voter) %> |
<%= link_to 'Back', admin_voters_path %>