config/routes.rb
Current::Application.routes.draw do

  root :to => "home#index"

  controller :sessions do
    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end

  get 'admin' => 'admin#index'

  namespace :admin do
    resources :alternatives
    resources :decisions
    resources :users
    resources :voters
    resources :votes, :except => [:new, :create, :edit, :update, :destroy]
  end

  resources :decision, :except => [:index, :create, :new, :show, :update, :edit, :destroy]

  get 'decision/:slug' => 'decision#new'

  post 'decision/:slug' => 'decision#create'

end

app/views/admin/_nav.html.erb
<ul class='h-nav'>

  <li><a href='<%= admin_decisions_path %>'>decisions</a>
    <%= render 'admin/nav1', :stem => 'admin_decision' %>
  </li>

  <li><a href='<%= admin_alternatives_path %>'>alternatives</a>
    <%= render 'admin/nav1', :stem => 'admin_alternative' %>
  </li>

  <li><a href='<%= admin_voters_path %>'>voters</a>
    <%= render 'admin/nav1', :stem => 'admin_voter' %>
  </li>

  <li><a href='<%= admin_votes_path %>'>votes</a>
    <%= render 'admin/nav1', :stem => 'admin_vote', :actions => [[nil, 'list']] %>
  </li>

  <li><a href='<%= admin_users_path %>'>users</a>
    <%= render 'admin/nav1', :stem => 'admin_user'  %>
  </li>

  <li style='float: right'>
    <%= link_to 'logout', logout_path, :method => :delete, :class => 'officious' %>
  </li>
</ul>

app/views/admin/_nav1.html.erb
<% ! defined?(actions) and actions = :all %>
<% :all == actions and actions = [[nil, 'List'], ['new', 'New']] %>
<% ! defined?(entity) and entity = /(?:^|_)([^_]+)\z/.match(stem)[1] %>
<ul>
  <% actions.each do |action| %>
  <li>
    <%  if Array === action
          _action, label = action
        else
          _action = label = action
        end
        _entity = _action.nil? ? "#{entity}s" : entity
    %>
    <a href="<%= nav_link(stem, _action) %>"><%= "#{label} #{_entity}" %></a>
  </li>
  <% end %>
</ul>

app/views/admin/index.html.erb
<h1>Admin Ass Section</h1>

<div class='section'>
  <div class='smug-subhead'>
    Use the awesome ass links in the above menu.
  </div>
</div>