config/routes.rb
Current::Application.routes.draw do

  root :to => "home#index"

  controller :sessions do
    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end

  get 'admin' => 'admin#index'

  namespace :admin do
    resources :alternatives
    resources :decisions
    resources :users
    resources :voters
    resources :votes, :except => [:new, :create, :edit, :update, :destroy]
  end

  resources :decision, :except => [:index, :create, :new, :show, :update, :edit, :destroy]

  get 'decision/:slug' => 'decision#new'

  post 'decision/:slug' => 'decision#create'

end

app/models/decision.rb
class Decision < ActiveRecord::Base
  attr_accessor :question_type # @todo
  def create_path
    "#{::Rails.root.to_s}/app/views/decision/#{intern}.html.erb" # @todo
  end
end

app/controllers/admin/decisions_controller.rb
class Admin::DecisionsController < ::AdminController
  respond_to :html, :json
  does :everything
end

app/controllers/decision_controller.rb
class DecisionController < ApplicationController
  skip_before_filter :authorize
  def new
    find_decision! or return
    render_form
  end

  def create
    find_decision! or return
    @vote = Vote.new(params[:vote]) # "token" | "human_hash"
    @vote.question_type = @decision.question_type || :yes_no_abstain # @todo
    @vote.decision_intern = @decision.intern
    @vote.parse_value
    if @vote.save
      msg = [success_msg, again_msg, public_identifier_msg].compact.join('  ')
      respond_to { |f| f.html { redirect_to('/', :notice => msg) } }
    else
      respond_to { |f| f.html { render_form } }
    end
  end
private
  def success_msg
    dv = @vote && @vote.display_value or return nil
    "You successfully voted #{dv} on the #{@vote.name} vote."
  end
  def again_msg
    ord = @vote && @vote.vote_ordinal or return
    ord > 1 or return
    num_prev = ord - 1
    pluralize = 1 == num_prev ? 'vote' : 'votes' # @todo etc
    "  (This vote overrides the previous " <<
      "#{1 == num_prev ? '' : "#{num_prev} " }" <<
      "#{pluralize} you have cast on this decision.)"
  end
  def public_identifier_msg
    s = @vote && @vote.voter && @vote.voter.public_identifier
    s && s != '' or return
    "You used the voting token with the public identifier #{s.inspect}."
  end
  def find_decision!
    slug = params['slug']
    if @decision = Decision.find_by_intern(slug)
      # @todo unhack!
      @decision.question_type = :multi_choice if /direlect/i =~ @decision.intern
      true
    else
      decision_not_found slug
    end
  end
  def decision_not_found slug
    @decision = Decision.new
    @decision.errors.add('base', "There is no decision on record with the name " <<
      "#{slug.inspect}")
    false # important
  end
  def populate_alternatives
    @alternatives = Alternative.all # @todo
    @alternatives.shuffle!
    @alternatives.each_with_index { |a, idx| a.random_ordinal_index = idx + 1 }
  end
  def render_form
    if @decision.create_path && File.exist?(@decision.create_path)
      populate_alternatives if :multi_choice == @decision.question_type
      render @decision.intern
    else
      @decision.errors.add('base', "for now we have no scaffolding for decisions. "<<
        "No view found for #{@decision.intern.inspect}.")
    end
  end
end

# format.xml  { render :xml => @vote.errors, :status => :unprocessable_entity }
# format.html { render :action => "new" }
# format.xml  { render :xml => @vote, :status => :created, :location => @vote }
# format.html { redirect_to(@vote, :notice => 'Vote was successfully created.') };

app/helpers/decision_helper.rb
module DecisionHelper
  def window_datetime dt
    return dt.strftime('%I:%M%p %Z, %a %m/%d, %Y')
    # "11:59pm EST, Tues 4/19, 2011." @todo
  end
end

app/views/admin/decisions/_form.html.erb
<%= form_for([:admin, @decision]) do |f| %>
  <% if @decision.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@decision.errors.count, "error") %> prohibited this decision from being saved:</h2>

      <ul>
      <% @decision.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :intern %><br />
    <%= f.text_field :intern %>
  </div>
  <div class="field">
    <%= f.label :open_at %><br />
    <%= f.datetime_select :open_at %>
  </div>
  <div class="field">
    <%= f.label :closed_at %><br />
    <%= f.datetime_select :closed_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/decisions/edit.html.erb
<h1>Editing decision</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_decision_path(@decision) %> |
<%= link_to 'Back', admin_decisions_path %>

app/views/admin/decisions/index.html.erb
<h1>Listing decisions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Intern</th>
    <th>Open at</th>
    <th>Closed at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @decisions.each do |decision| %>
  <tr>
    <td><%= decision.name %></td>
    <td><%= decision.intern %></td>
    <td><%= decision.open_at %></td>
    <td><%= decision.closed_at %></td>
    <td><%= link_to 'Show', admin_decision_path(decision) %></td>
    <td><%= link_to 'Edit', edit_admin_decision_path(decision) %></td>
    <td><%= link_to 'Destroy', admin_decision_path(decision), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Decision', new_admin_decision_path %>

app/views/admin/decisions/new.html.erb
<h1>New decision</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_decisions_path %>

app/views/admin/decisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @decision.name %>
</p>

<p>
  <b>Intern:</b>
  <%= @decision.intern %>
</p>

<p>
  <b>Open at:</b>
  <%= @decision.open_at %>
</p>

<p>
  <b>Closed at:</b>
  <%= @decision.closed_at %>
</p>


<%= link_to 'Edit', edit_admin_decision_path(@decision) %> |
<%= link_to 'Back', admin_decisions_path %>