config/routes.rb
Current::Application.routes.draw do

  root :to => "home#index"

  controller :sessions do
    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end

  get 'admin' => 'admin#index'

  namespace :admin do
    resources :alternatives
    resources :decisions
    resources :users
    resources :voters
    resources :votes, :except => [:new, :create, :edit, :update, :destroy]
  end

  resources :decision, :except => [:index, :create, :new, :show, :update, :edit, :destroy]

  get 'decision/:slug' => 'decision#new'

  post 'decision/:slug' => 'decision#create'

end

app/models/user.rb
class User < ActiveRecord::Base

  class << self
    def encrypt_password password, salt
      Digest::SHA2.hexdigest(password + "wibble" + salt)
    end
    def authenticate(name, password)
      if user = find_by_name(name)
        if user.hashed_password == encrypt_password(password, user.salt)
          user
        end
      end
    end
  end

  validates :name, :presence => true, :uniqueness => true
  validates :password, :confirmation => true

  attr_accessor :password_confirmation
  attr_reader   :password

  validate :password_must_be_present

  def password= password
    @password = password
    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end

private

  def password_must_be_present
    errors.add(:password, "Missing password") unless hashed_password.present?
  end
  def generate_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ::AdminController
  respond_to :html, :json
  does :everything
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

	<div class="field">
	  <%= f.label :password, 'Password' %><br />
	  <%= f.password_field :password, :size => 40 %>
	</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Listing users</h1>

<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', admin_user_path(user) %></td>
    <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
    <td><%= link_to 'Destroy', admin_user_path(user), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>